"""3rd  migrations

Revision ID: bde631285a02
Revises: d2d7c8d5685b
Create Date: 2022-01-04 17:15:52.471266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde631285a02'
down_revision = 'd2d7c8d5685b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('img_path', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'img_path')
    # ### end Alembic commands ###
