"""2nd  migrations

Revision ID: d2d7c8d5685b
Revises: 83954629eada
Create Date: 2022-01-04 16:37:44.896093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d7c8d5685b'
down_revision = '83954629eada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('hobby', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('fav_food', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('fav_movie', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('fav_game', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('marriage', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'marriage')
    op.drop_column('user', 'fav_game')
    op.drop_column('user', 'fav_movie')
    op.drop_column('user', 'fav_food')
    op.drop_column('user', 'hobby')
    op.drop_column('user', 'location')
    # ### end Alembic commands ###
